// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    internal partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Domain.Entities.Course", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("DayOfWeek")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal>("Price")
                    .HasColumnType("numeric");

                b.HasKey("Id");

                b.ToTable("Courses");
            });

            modelBuilder.Entity("Domain.Entities.Course", b =>
            {
                b.OwnsOne("Domain.Entities.TimeOfDay", "EndTime", b1 =>
                {
                    b1.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b1.Property<byte>("Hour")
                        .HasColumnType("smallint");

                    b1.Property<byte>("Minute")
                        .HasColumnType("smallint");

                    b1.HasKey("CourseId");

                    b1.ToTable("Courses");

                    b1.WithOwner()
                        .HasForeignKey("CourseId");
                });

                b.OwnsOne("Domain.Entities.TimeOfDay", "StartTime", b1 =>
                {
                    b1.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b1.Property<byte>("Hour")
                        .HasColumnType("smallint");

                    b1.Property<byte>("Minute")
                        .HasColumnType("smallint");

                    b1.HasKey("CourseId");

                    b1.ToTable("Courses");

                    b1.WithOwner()
                        .HasForeignKey("CourseId");
                });
            });
#pragma warning restore 612, 618
        }
    }
}
